# Site settings

title: Tianhui Yang # Title of your site
email: ytianhui2004@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Tianhui Yang's personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ytianhui.github.io"  # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

github_username:      example  # Replace this with your GitHub username
linkedin_username:    example  # Replace this with your LinkedIn username
facebook_username:    example  # Replace this with your Facebook username
dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown
